### ISSUE TITLE
Where does the grayscale image come from?

### ISSUE THREAD

**Issue by silenye** [rapidrabbit76/Style-Transfer-for-Anime-Sketches#1]
Hello, I would like to ask whether the grayscale image is converted from a label to a grayscale image?

**Comment by silenye** [comment]
Do you use the guide decoder during training, but do you not use it during inference?

**Comment by rapidrabbit76** [comment]
hello, @silenye 

For this repo, training didn't work well for my dataset.
Therefore, I would like to inform you that the answer I give may not be the correct answer.

There is no official implementation so I am also having a hard time.

1. guide decoders
From what I understand, the guide decoder is used in the training process.
Used as a term for loss.

2. datasets
The data set basically used the "Danbooru" data set.
Line-art image was extracted separately from the color image using XDoG.
Use line-art images and color images in pairs.

dataset structure is like this

```
.
└── dataset
 ├── color
 │   ├── 1.png
 │   ├── 2.png
 │   └── 3.png
 └── line
     ├── 1.png
     ├── 2.png
     └── 3.png
```

I hope this helps!
and if you succeed, I'd appreciate contributing to the repo.
